### ISSUE TITLE
Ability to turn up debugging using a variable

### ISSUE THREAD

**Issue by clil16** [arohou/gP2S#3]
Hello,
I was wondering if there was a way to turn debugging up for gp2s-service?  I think it would be really useful to be able to specify the debugging level in the docker-compose.yml file.

**Comment by arohou** [comment]
Pleas try to add `LOGGING_LEVEL_ROOT: DEBUG` to the `gp2s-service:environment` section of `docker-compose`. Does that work / do what you hoped it would?

In general, we use the spring framework logging features. You can find out more at https://docs.spring.io/spring-boot/docs/current/reference/html/boot-features-logging.html

**Comment by clil16** [comment]
I set that variable and while I saw more output it did not contain everything I expected so that must be due to the spring framework logging.
The issue I was trying to resolve by turning the logging up I was able to resolve using another method.

**Comment by arohou** [comment]
Thanks for the update! Sorry the logging didn't deliver what you were hoping!
